# Generated by Django 2.2 on 2019-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('1', 'ㅆㅎㅌㅊ'), ('2', 'ㅎㅌㅊ'), ('3', 'ㅍㅌㅊ'), ('4', 'ㅅㅌㅊ'), ('5', 'ㅆㅅㅌㅊ')], max_length=50),
        ),
    ]
