# Generated by Django 2.2 on 2019-04-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewapp', '0002_auto_20190411_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('ㅆㅎㅌㅊ', 'ㅆㅎㅌㅊ'), ('ㅎㅌㅊ', 'ㅎㅌㅊ'), ('ㅍㅌㅊ', 'ㅍㅌㅊ'), ('ㅅㅌㅊ', 'ㅅㅌㅊ'), ('ㅆㅅㅌㅊ', 'ㅆㅅㅌㅊ')], max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookreviewapp.Review')),
            ],
        ),
    ]
