# Generated by Django 2.2.1 on 2019-05-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewapp', '0003_auto_20190430_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
